#!/bin/bash

dir="$HOME/.config/loc"
store="$dir/store"

[ -e "$dir" ] || mkdir -p "$dir"
[ -e "$store" ] || touch "$store"


loc_selector_dmenu() {
	dmenu -i -p "$1" -l 12
}
loc_selector_fzf() {
	fzf -e --prompt "$1: " --height 12 --reverse
}
loc_selector() {
	loc_selector_fzf "$@"
}


loc_append() { # (path = ".")
	path="$(realpath "${1:-.}")"

	(echo "$path"; grep -vxF "$path" "$store") | sponge "$store"
}

loc_remove() { # (path = ".")
	path="$(realpath "${1:-.}")"

	grep -vxF "$path" "$store" | sponge "$store"
}

loc_size() {
	cat "$store" | wc -l
}

loc_clear() {
	> "$store"
}

_loc_go() { # (path)

	echo "$1"
	cd "$1"
}

loc_select() { # (exclude = "")

	exclude=""
	[ -z "$1" ] || exclude="$(realpath "$1")"

	target="$( (cat "$store" | grep -vxF "$exclude" ; cat "$store" | grep -xF "$exclude"; echo "> remove") | loc_selector "loc")"
	[ "$?" -ne "0" ] && return

	if [ "$target" = "> remove" ]; then

		target="$( (echo "> all"; cat "$store") | loc_selector "loc remove")"
		[ "$?" -ne "0" ] && return

		if [ "$target" = "> all" ]; then
			loc_clear
		else
			loc_remove "$target"
		fi

	else

		_loc_go "$target"
	fi
}

loc_go() {

	exclude="$(realpath ".")"
	target="$(cat "$store" | grep -vxF "$exclude" | head -n1)"

	[ -n "$target" ] && _loc_go "$target"
}

case "$1" in
	"")
		[ "1" -gt "$(loc_size)" ] || loc_select "."
	;;
	"clear")
		loc_clear
	;;
	"remove")
		loc_remove "$2"
	;;
	"add")
		loc_append "$2"
	;;
	"go")
		loc_go
	;;
	"edit")
		$EDITOR "$store"
	;;
	*)
		loc_append "$1"
		[ "2" -gt "$(loc_size)" ] || loc_select
	;;
esac

